sudo: required
services:
  - docker

before_install:
  - docker build -t my-app -f Dockerfile.dev .

script:
  - docker run -e CI=true my-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react-app'
  env: 'DockerReactApp-env'
  bucket_name: 'elasticbeanstalk-us-east-2-162349975941'
  bucket_path: 'docker-react-app'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
